org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
